### ISSUE TITLE
Unexpected error: Error while running generator ListGen: 'maxCount' cannot be negative

### ISSUE THREAD

**Issue by ptetau** [nth-commit/GalaxyCheck#169]
This was an unexpected error because `maxCount` is internal for this generator. Here is a minimal test case:

```
  [Property]
        public IGen<Test> errar() =>
            from m in Gen.Int32().GreaterThanEqual(1)
            from n in Gen.List(Gen.Int32()).WithCountGreaterThanEqual(m)
            select Property.ForThese(() =>
            {
                return n.Count > 0;
            }
```

**Stack trace:**
`PlaycenterSolver.Tests.AboutCapacity.errar

GalaxyCheck.Exceptions+GenErrorException: Error while running generator ListGen: 'maxCount' cannot be negative

GalaxyCheck.Exceptions+GenErrorException
Error while running generator ListGen: 'maxCount' cannot be negative
   at GalaxyCheck.Extensions.MapTransitionToIterationOrIgnore[T](AbstractTransition`1 transition, Boolean enablePresentationalInference)
   at GalaxyCheck.Extensions.<>c__DisplayClass35_0`1.<AggregateTransitions>b__1(ValueTuple`2 x)
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at GalaxyCheck.Internal.EnumerableExtensions.ScanInParallel[TSource,TAccumulator](IEnumerable`1 input, TAccumulator seed, Func`3 next)+MoveNext()
   at System.Linq.Enumerable.SelectEnumerableIterator`2.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at System.Collections.Immutable.ImmutableExtensions.FallbackWrapper`1.get_Count()
   at System.Collections.Immutable.ImmutableList`1.CreateRange(IEnumerable`1 items)
   at System.Collections.Immutable.ImmutableList`1.AddRange(IEnumerable`1 items)
   at System.Collections.Immutable.ImmutableList.ToImmutableList[TSource](IEnumerable`1 source)
   at GalaxyCheck.Extensions.AggregateTransitions[T](IEnumerable`1 transitions, PropertyOptions options)
   at GalaxyCheck.Extensions.Check[T](Property`1 property, Nullable`1 iterations, Nullable`1 seed, Nullable`1 size, Nullable`1 shrinkLimit, String replay, Boolean deepCheck)
   at GalaxyCheck.Extensions.Assert[T](Property`1 property, Nullable`1 iterations, Nullable`1 seed, Nullable`1 size, Nullable`1 shrinkLimit, String replay, Func`2 formatReproduction, Func`2 formatMessage)
   at GalaxyCheck.Xunit.Internal.PropertyAssertRunner.Run(PropertyRunParameters parameters, ITestOutputHelper testOutputHelper)
   at GalaxyCheck.Xunit.Internal.PropertyTestCase.RunAsync(IMessageSink diagnosticMessageSink, IMessageBus messageBus, Object[] constructorArguments, ExceptionAggregator aggregator, CancellationTokenSource cancellationTokenSource)
`

**Comment by nth-commit** [comment]
Hey @ptetau, just saw this. It's definitely unexpected. I'll look into it.

**Comment by nth-commit** [comment]
I was thinking about this whilst doing the dishes and figured it out.

The list generator has not been programmed to handle the overflow case (I hadn't thought about this scenario). In your example, you're asking for lists greater than the generated integer. In some cases, the generated integer will be int.MaxValue. The list generator takes the minCount it's given and adds 10, and it does that without overflow protection. So int.MaxValue wraps around to int.MinValue + 9 (which is less than the minCount of int.MaxValue). So yep, there's a bug there.

The reason I haven't thought about big lists, is because a list usually goes hand-in-hand with iteration. So if you're generating big lists, they'll probably grind your system to a halt (in not the way you intended). In you're example, you generating lists with a count of up to int.MaxValue. Just allocating all that memory is going to be stressful for your test.

Maybe there should be a safety control around list count to remove the pit-of-failure that exists with a generator setup similar to the one you described. Users would have to explicitly turn off this control if they wanted to generate big lists. Actually, there is precedent for this e.g. in Gen.Infinite. And a list of count int.MaxValue might as well be infinite.

https://github.com/nth-commit/GalaxyCheck/blob/ba0c33ed0a020684ee9b1c031f0865689c9fa4a7/src/GalaxyCheck/Gens/InfiniteGen.cs#L8-L20
